import type { Metadata } from 'next';
import { Suspense } from 'react';
import CompanyPage from '@/components/CompanyPage';

export const metadata: Metadata = {
  title: 'Marcus Hansen | Built For Your Team',
  description: 'A personalized fit page, generated by an AI pipeline Marcus Hansen built.',
  robots: { index: false, follow: false },
};

export default function ForPage() {
  return (
    <Suspense>
      <CompanyPage />
    </Suspense>
  );
}
